# Generated by Django 4.2 on 2023-08-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.AddField(
            model_name="actor",
            name="movie",
            field=models.ManyToManyField(
                blank=True, related_name="actor", to="movies.movie"
            ),
        ),
        migrations.AddField(
            model_name="director",
            name="movie",
            field=models.ManyToManyField(
                blank=True, related_name="director", to="movies.movie"
            ),
        ),
    ]
