# Generated by Django 4.2 on 2023-08-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_remove_movie_director_director_movie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="director",
            name="movie",
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="movies.director",
            ),
            preserve_default=False,
        ),
    ]
