# Generated by Django 4.2 on 2023-08-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_remove_director_movie_movie_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actor",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="director",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(
                default="random", max_length=50, unique=True, verbose_name="name"
            ),
        ),
    ]
