# Generated by Django 4.2 on 2023-08-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_alter_actor_name_alter_director_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(blank=True),
        ),
    ]
