# Generated by Django 4.2 on 2023-08-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_alter_actor_name_alter_director_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="name"),
        ),
    ]
